### ISSUE TITLE
Import IBMSAFR-Spark Code base

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/spark-poc#9] opened 2020-08-28 21:30 UTC
OMP Scan is complete of the IBMSAFR-Spark repo and it is authorized to bring into this repo.  To do so, I suggest copying files in a branch locally, and pushing the branch with a PR to this repo, so that files within this repo are not overwritten.

**Comment by KipTwitchell** [comment] 2020-08-31 13:51
consider removing code that is not Apache 2.0 compliant.

**Comment by SaPeresi** [comment] 2020-10-14 15:21
This is a duplicate of item 10 - this can be closed.

**Closed by SaPeresi** 2020-10-14 15:21 UTC
Labels: meeting
